---
title: "vis 2"
author: "David"
date: "2024-10-01"
output: html_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(patchwork)
library(haven)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y =tmax, color = name)) +
  geom_point(alpha = 0.3) +
  labs(
    tittle = "Temperature scatterplot",
    x = "Minimum Temperature(C)",
    y = "Maximum Temperature(C)",
    color = "location",
    caption = "Weather data taken from rnoaa package for three stations."
  )
```


Look at scale of axis
```{r}
weather_df |>
  ggplot(aes(x = tmin, y =tmax, color = name)) +
  geom_point(alpha = 0.3) +
  labs(
    tittle = "Temperature scatterplot",
    x = "Minimum Temperature(C)",
    y = "Maximum Temperature(C)",
    color = "location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 20),
    labels = c("-15", "0", "20")
  ) +
  scale_y_continuous(
    limits = c(0, 30),
    transform = "sqrt",
    position = "right"
  )
```

Look at color
```{r}
weather_df |>
  ggplot(aes(x = tmin, y =tmax, color = name)) +
  geom_point(alpha = 0.3) +
  labs(
    tittle = "Temperature scatterplot",
    x = "Minimum Temperature(C)",
    y = "Maximum Temperature(C)",
    color = "location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 20),
    labels = c("-15", "0", "20")
  ) +
  scale_y_continuous(
    limits = c(0, 30)
  ) +
  scale_color_hue(h = c(100, 400))
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y =tmax, color = name)) +
  geom_point(alpha = 0.3) +
  labs(
    tittle = "Temperature scatterplot",
    x = "Minimum Temperature(C)",
    y = "Maximum Temperature(C)",
    color = "location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  viridis::scale_color_viridis(
    name = "Location",  # alphabetic order
    discrete = TRUE
  )
```

## Themes

```{r}
ggp_scatterplot =
  weather_df |>
  ggplot(aes(x = tmin, y =tmax, color = name)) +
  geom_point(alpha = 0.3) +
  labs(
    tittle = "Temperature scatterplot",
    x = "Minimum Temperature(C)",
    y = "Maximum Temperature(C)",
    color = "location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  viridis::scale_color_viridis(
    discrete = TRUE
  )

ggp_scatterplot +
  theme(legend.position = "bottom")

ggp_scatterplot +
  theme_bw() +
  theme(legend.position = "bottom")

ggp_scatterplot + 
  theme_classic() + 
  theme(legend.position = "bottom")
```

```{r}
weather_df |>
  ggplot(aes(x = date, y =tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = TRUE) +
  labs(
    tittle = "Temperature scatterplot",
    x = "Date",
    y = "Maximum Temperature(C)",
    size = "Precipitation",
    color = "location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  viridis::scale_color_viridis(
    discrete = TRUE
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

```

```{r}
central_park_df =
  weather_df |>
  filter(name == "CentralPark_NY")

molokai_df =
  weather_df |>
  filter(name == "Molokai_HI")

molokai_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park_df)

```

## Multiple panels
```{r}
weather_df |>
  ggplot(aes(x= tmax, fill = name)) +
  geom_density() +
  facet_grid(. ~ name)
```

```{r}
ggp_tmax_tmin =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3)

ggp_tmax_density =
  weather_df |>
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3)

ggp_tmax_date =
  weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE)

(ggp_tmax_tmin + ggp_tmax_density) / ggp_tmax_date
  
```

## Data manipulation

```{r}
weather_df |>
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |>
  ggplot(aes(x= name, y = tmax, fill = name)) +
  geom_violin(alpha = 0.5)
```

```{r}
pulse_df =
  read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    col = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |>
  mutate(visit = ifelse(visit == "bl", "00m", visit))

pulse_df |>
  ggplot(aes(x = visit, y = bdi_score)) +
  geom_boxplot()
  
```

```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  mutate(
    sex = 
      case_match(
        sex, 
        1 ~ "male", 
        2 ~ "female")) |>
  pivot_longer(
    col = pd_ears:pd_walk,
    values_to = "pn_day",
    names_to = "outcome"
  )

litter_data = 
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "tx_day"), sep = 3)

fas_data = left_join(pup_data, litter_data, by = "litter_number") 

fas_data |>
  drop_na() |>
  ggplot(aes(x = dose, y = pn_day)) +
  geom_boxplot() +
  facet_grid(tx_day ~ outcome)
```












