---
title: "Vis 1"
author: "David"
date: "2024-09-26"
output: github_document
---

Load R packages

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(ggridges)
```



```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Making our first plot
```{r}
ggp_weather_scatterplot =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_weather_scatterplot
```

## fancier scatterplot
```{r}
ggp_colored_weather_scatterplot =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE)

ggp_colored_weather_scatterplot
```

use facet
```{r}
ggp_facet_weather_scatterplot =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

ggp_facet_weather_scatterplot
```

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```


```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax_f = tmax * 9 / 5 + 32,
    tmin_f = tmin * 9 / 5 + 32
  ) |>
  ggplot(aes(x = tmin_f, y = tmax_f)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

```{r}
weather_df |>
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram() +
  facet_grid(. ~ name)
```

```{r}
weather_df |>
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge", binwidth = 2)
#dodge could resolve lapping issue
```

```{r}
weather_df |>
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3, adjust = 0.5, color = "blue")
```

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin, fill = name)) +
  geom_boxplot()
```

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin, fill = name)) +
  geom_violin(alpha = 0.5) +
  stat_summary(fun = "median", color = "black")
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = name)) +
  geom_density_ridges(scale = 0.8)
```

```{r}
weather_df |>
ggplot(aes(x = prcp)) +
  geom_density(aes(fill = name), alpha = 0.5)

weather_df |>
  ggplot(aes(x = name, y = prcp)) +
  geom_boxplot()
```

## saving plot
```{r}
ggp_facet_weather_scatterplot =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

ggsave("ggp_facet_weather_scatterplot.pdf", ggp_facet_weather_scatterplot, width = 8, height = 6)
```




